MotChallenge2DBox
pred
Traceback (most recent call last):
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/eval.py", line 187, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/datasets/_base_dataset.py", line 87, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/datasets/mot_challenge_2d_box.py", line 240, in _load_raw_file
    time_data = np.asarray(read_data[time_key], dtype=np.float)
  File "/opt/conda/envs/gtr/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
pred
Traceback (most recent call last):
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/eval.py", line 193, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/metrics/hota.py", line 30, in eval_sequence
    res[field] = np.zeros((len(self.array_labels)), dtype=np.float)
  File "/opt/conda/envs/gtr/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
pred
Traceback (most recent call last):
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/eval.py", line 193, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/metrics/identity.py", line 71, in eval_sequence
    res['IDFN'] = fn_mat[match_rows, match_cols].sum().astype(np.int)
  File "/opt/conda/envs/gtr/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
pred
Traceback (most recent call last):
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/eval.py", line 191, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/datasets/mot_challenge_2d_box.py", line 378, in get_preprocessed_seq_data
    raise(TrackEvalException('Attempting to evaluate using invalid gt classes. '
gtr.tracking.trackeval.utils.TrackEvalException: Attempting to evaluate using invalid gt classes. This warning only triggers if preprocessing is performed, e.g. not for MOT15 or where prepropressing is explicitly disabled. Please either check your gt data, or disable preprocessing. The following invalid classes were found in timestep 0: -1





MotChallenge2DBox
pred
Traceback (most recent call last):
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/eval.py", line 191, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/datasets/mot_challenge_2d_box.py", line 335, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "/data2/SMVU/GTR/gtr/tracking/trackeval/datasets/_base_dataset.py", line 310, in _check_unique_ids
    raise TrackEvalException(exc_str)
gtr.tracking.trackeval.utils.TrackEvalException: Ground-truth has the same ID more than once in a single timestep (seq: playing_basketball_with_child/VAqxheTIztU_0, frame: 69, ids: 3)





